### ISSUE TITLE
(stty 'raw) does not behave like stty raw in the shell

### ISSUE THREAD

**Issue by dieggsy** [fadein/chicken-stty#1]
currently, raw is defined as the combination of these flags:
```scheme
   (raw      combine  (not ignbrk brkint ignpar parmrk
                           inpck istrip inlcr igncr icrnl))
```

But according to `man stty` on linux, `raw` is equivalent to:

```
-ignbrk  -brkint  -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl
-ixon -ixoff -icanon -opost -isig -iuclc -ixany  -imaxbel  -xcase
```
Could we add the relevant extra flags, or is there a reason it's implemented the current way? 

As a side note: the egg doesn't actually define the `xcase` and `iuclc` flags - how come?

**Comment by fadein** [comment]
@dieggsy I honestly don't know why this egg doesn't provide the behavior you describe.  I didn't write the egg, my contribution to this egg was porting it over to C5.  But I'm happy to accept a patch ;)
